FAQ page
srm-kzilla/fury pull request #378
Opened 2023-08-23 19:22 UTC by SaanviKumar13

## Description

Adds FAQ page in `client/landing`
Adds link to faq page in side bar in `client/dashboard`

## Laptop
![image](https://github.com/srm-kzilla/fury/assets/113087236/b7824ea1-0a78-4956-bec5-1daefe11e1fd)
![image](https://github.com/srm-kzilla/fury/assets/113087236/ccf7f8aa-b083-4433-93e6-709842f9ee93)

## Mobile
![image](https://github.com/srm-kzilla/fury/assets/113087236/4f172174-6ec0-4423-9f21-baef24fe9423)

## Sidebar in dashboard
![image](https://github.com/srm-kzilla/fury/assets/113087236/32407188-3974-49a6-b9e0-6f3e394405c3)

2023-08-23 20:54 UTC, shawshankkumar approved these changes

2023-08-24 05:09 UTC, sm-sami requested changes
The padding in desktop can be increased, the offset to the answers in mobile is weird and. Q1, Q2 also does not seem nice, try something else maybe.

2023-08-24 05:09 UTC, sm-sami commented on client/dashboard/app/components/Sidebar.tsx
> +              className={
This link can never be active! (cause it is external)

2023-08-24 05:09 UTC, sm-sami commented on client/dashboard/app/components/Sidebar.tsx
> +              to="https://recruitment.srmkzilla.net/faq"
Instead of hardcoding, expose `LANDING_URL` to the client by including it in the `LoaderFunction` in `root.tsx`

2023-08-24 05:09 UTC, sm-sami commented on client/landing/components/Footer.tsx
>            {/* <a href="https://dashboard.kzilla.xyz" target="_blank"> */}
oh this can be uncommented with the link pointing to https://dash.kzilla.xyz and remove the `target` attribute

2023-08-24 05:09 UTC, sm-sami commented on client/landing/utils/faqQuestion.ts
rename the directory as `constants`

2023-08-24 05:09 UTC, sm-sami commented on client/landing/utils/faqQuestion.ts
> +  export default faqs;
This file does not seem to be formatted with prettier

2023-08-24 05:20 UTC, sm-sami commented on client/landing/components/Footer.tsx
> +                FAQ's
just `FAQs`, remove the apostrophe

2023-08-24 12:26 UTC, sm-sami requested changes
Increase the padding at the bottom
![image](https://github.com/srm-kzilla/fury/assets/64266012/f46f47a9-badb-4860-aebd-88261e1da9cc)

also increase the font size, and I don't think the favicon is there for the page, have a look

2023-08-24 12:26 UTC, sm-sami commented on client/landing/components/Footer.tsx
> +              <a href="/faq" target="blank">
remove target here, just open it in the same tab

2023-08-24 12:27 UTC, sm-sami commented on client/dashboard/app/components/Sidebar.tsx
> +  const data = useLoaderData();
There is a helper for this, `getEnv` in `utils/env.ts`

2023-08-24 18:34 UTC, merged