Fixes bypass to Tech-p
srm-kzilla/fury pull request #409
Opened 2023-08-29 07:37 UTC by SaanviKumar13

### Description

Prevents bypass to technical projects if application exists.

closes #408

2023-08-29 07:42 UTC, shawshankkumar requested changes

2023-08-29 07:42 UTC, shawshankkumar commented on client/dashboard/app/routes/applications.technical-project.tsx
>  } from "@remix-run/node";
no need to put a full stop after commit names

2023-08-29 07:42 UTC, shawshankkumar commented on client/dashboard/app/routes/applications.technical-project.tsx
> +  const userDetails = await getUserDetails(request);
does this check for technicalp specifically? or any domain. Can you check what happens when you have filled the form for events and try to fill techp

2023-08-29 07:43 UTC, shawshankkumar commented on client/dashboard/app/routes/applications.technical-project.tsx
> +    if (!(applicationExists.status === "draft")) {
also, i dont think its a good idea to use "draft" everywhere. create enum or create an object with as const In a shared folder and use it everywhere for things like pending, and other constant things.

2023-08-29 15:16 UTC, sm-sami requested changes

2023-08-29 15:16 UTC, sm-sami commented on client/dashboard/app/utils/constants.ts
move this to `types/index.ts`

2023-08-29 15:16 UTC, sm-sami commented on client/dashboard/app/routes/applications.technical-project.tsx
> +  const userDetails = await getUserDetails(request);
Do the destructing here itself

2023-08-30 10:22 UTC, sm-sami approved these changes

2023-08-30 10:23 UTC, merged